import tailwindcss from "@tailwindcss/vite";
import vinext from "vinext";
import { defineConfig } from "vite";

export default defineConfig({
  // Cloudflare Workers wiring is generated by `vinext deploy`; keep this config
  // minimal so `vinext dev` and `vinext build` work locally without it.
  plugins: [tailwindcss(), vinext()],
  // lucide-react ships many small client modules; excluding it from dep
  // pre-bundling keeps the RSC/client optimizer consistent (per vinext hint).
  optimizeDeps: {
    exclude: ["lucide-react"],
  },
});
